name: Debug SSH to EC2

on:
  workflow_dispatch:

jobs:
  debug-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Check key format
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} "echo 'SSH success!'"
